on: push
name: Document
jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade setuptools wheel
          pip install -r docs/requirements.txt
      - name: Build Sphinx documentation
        run: |
          PYTHONPATH=. sphinx-build docs/ docs/_build/
          touch docs/_build/.nojekyll
      - name: Build hypertext fuse database
        run: |
          PYTHONPATH=. python -m util.genhtml
      - name: Publish documentation
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/_build/
          clean: true
